### ISSUE TITLE
Recreation 

### ISSUE THREAD

**Issue by AaHug** [johanwheeler/ch32-fireplace#1]
I'm pretty amature at this, and have a much more knowledge friend helping me.  He was trying to upload the PCB files to jlcpcb.  It wasn't generating a needed parts list.  I've been told we are looking for a Bill of Materials and a Placement file.  Any help would be appreciated.

**Comment by Muoshy** [comment]
Good catch! Seems like the BOM and placements files (.csv) were excluded by our gitignore. It should be fixed now. You can find them in PCBs/Back/Production. Otherwise, you can generate the BOM and placement files with the fabrication toolkit plugin in KiCad. The KiCad files should contain the JLCPCB part numbers. 

Let me know if you need additional help or if I can close the issue.

**Comment by AaHug** [comment]
It's fixed now.  Thank you so much for your help.

Aaron Hugenberg
